service: meguiluzortiz-hello-world-sls-app
# app and org for use with dashboard.serverless.com
app: hello-world-sls-app
org: eguiluzmanuel

provider:
  name: aws
  region: us-east-1
  profile: default
  stage: dev
  runtime: nodejs12.x
  versionFunctions: false
  stackName: ${self:service}-stack
  deploymentBucket:
    name: ${self:service}-bucket

functions:
  index:
    handler: handler.index
    name: hello-world-index
    timeout: 10 # optional, in seconds, default is 6
    # events:
    #   - http:
    #       path: /
    #       method: get
    #  - schedule: rate(10 minutes)
    environment:
      TEXT_HELLO: Hello

plugins:
  - serverless-offline
